version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2

    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xms3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test jacoco:report

      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
      - run: ./codecov -t 7b1f26a2-f466-4832-9038-234271c5ab95 -s target/surefire-reports